name: Release Docker image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Download serving model from S3
        run: |
          mkdir -p artifacts/serving
          aws s3 cp "${{ vars.S3_MODEL_URI }}" artifacts/serving/model.joblib

      - name: Set image tag
        id: meta
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=manual" >> "$GITHUB_OUTPUT"
          fi

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
          --build-arg GIT_COMMIT=${{ github.sha }} \
          -t ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.tag }} .
          docker tag ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.tag }} ghcr.io/${{ github.repository }}:latest

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.tag }}
          docker push ghcr.io/${{ github.repository }}:latest